// ==========================================================================
// 📖 华文智能互动学习阅读器 - 词汇数据库 (data.js)
// ==========================================================================

const lessonTitle = "阿婆的菜园";

const lessonData = [
    // ===== 第1段 =====
    ["“", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["跟", "gēn", "with", "dengan"],
    ["你", "nǐ", "you", "awak"],
    ["一起", "yī qǐ", "together", "bersama"],
    ["去", "qù", "go", "pergi"],
    ["。", "", "", ""],
    ["”", "", "", ""],
    ["小孙女", "xiǎo sūn nǚ", "little granddaughter", "cucu perempuan kecil"],
    ["连忙", "lián máng", "hurriedly", "segera"],
    ["说", "shuō", "said", "berkata"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第2段

    // ===== 第2段 =====
    ["阿婆", "ā pó", "grandmother", "nenek"],
    ["牵着", "qiān zhe", "holding", "memegang"],
    ["小孙女", "xiǎo sūn nǚ", "little granddaughter", "cucu perempuan kecil"],
    ["的", "de", "", ""],
    ["手", "shǒu", "hand", "tangan"],
    ["，", "", "", ""],
    ["走出", "zǒu chū", "walked out", "keluar"],
    ["屋子", "wū zi", "house", "rumah"],
    ["，", "", "", ""],
    ["走向", "zǒu xiàng", "walked towards", "berjalan ke arah"],
    ["村尾", "cūn wěi", "end of the village", "hujung kampung"],
    ["那片", "nà piàn", "that", "itu"],
    ["小小", "xiǎo xiǎo", "small", "kecil"],
    ["的", "de", "", ""],
    ["菜园", "cài yuán", "vegetable garden", "kebun sayur"],
    ["。", "", "", ""],
    ["篱笆", "lí ba", "fence", "pagar"],
    ["旁", "páng", "beside", "sebelah"],
    ["的", "de", "", ""],
    ["野猫", "yě māo", "wild cat", "kucing liar"],
    ["看到", "kàn dào", "saw", "melihat"],
    ["她们", "tā men", "them", "mereka"],
    ["，", "", "", ""],
    ["也", "yě", "also", "juga"],
    ["悄悄地", "qiāo qiāo de", "quietly", "diam-diam"],
    ["跟", "gēn", "follow", "mengikuti"],
    ["了", "le", "", ""],
    ["上来", "shàng lái", "up", "naik"],
    ["。", "", "", ""],
    ["邻居", "lín jū", "neighbours", "jiran"],
    ["家", "jiā", "home", "rumah"],
    ["的", "de", "", ""],
    ["小男孩", "xiǎo nán hái", "little boy", "budak lelaki kecil"],
    ["听见", "tīng jiàn", "heard", "mendengar"],
    ["动静", "dòng jìng", "movement", "pergerakan"],
    ["后", "hòu", "after", "selepas"],
    ["，", "", "", ""],
    ["也", "yě", "also", "juga"],
    ["从", "cóng", "from", "dari"],
    ["矮墙", "ǎi qiáng", "low wall", "dinding rendah"],
    ["后面", "hòu miàn", "behind", "belakang"],
    ["探出", "tàn chū", "poked out", "menjenguk"],
    ["头", "tóu", "head", "kepala"],
    ["来", "lái", "come", "datang"],
    ["，", "", "", ""],
    ["一起", "yī qǐ", "together", "bersama"],
    ["加入", "jiā rù", "join", "menyertai"],
    ["了", "le", "", ""],
    ["她们", "tā men", "their", "mereka"],
    ["的", "de", "", ""],
    ["行列", "háng liè", "ranks", "barisan"],
    ["。", "", "", ""],
    ["于是", "yú shì", "so", "maka"],
    ["，", "", "", ""],
    ["村子", "cūn zi", "village", "kampung"],
    ["里", "lǐ", "in", "dalam"],
    ["好几个", "hǎo jǐ gè", "several", "beberapa"],
    ["孩子", "hái zi", "children", "kanak-kanak"],
    ["都", "dōu", "all", "semua"],
    ["聚拢", "jù lǒng", "gathered", "berkumpul"],
    ["在", "zài", "at", "di"],
    ["菜园", "cài yuán", "vegetable garden", "kebun sayur"],
    ["门口", "mén kǒu", "entrance", "pintu masuk"],
    ["，", "", "", ""],
    ["仿佛", "fǎng fú", "as if", "seolah-olah"],
    ["组成", "zǔ chéng", "formed", "membentuk"],
    ["了", "le", "", ""],
    ["一支", "yī zhī", "a", "satu"],
    ["声势浩大", "shēng shì hào dà", "grand", "megah"],
    ["的", "de", "", ""],
    ["劳动队伍", "láo dòng duì wǔ", "labour team", "pasukan buruh"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第3段

    // ===== 第3段 =====
    ["“", "", "", ""],
    ["你", "nǐ", "you", "awak"],
    ["在", "zài", "at", "di"],
    ["哪儿", "nǎ ér", "where", "di mana"],
    ["？", "", "", ""],
    ["”", "", "", ""],
    ["阿婆", "ā pó", "grandmother", "nenek"],
    ["的", "de", "", ""],
    ["询问声", "xún wèn shēng", "voice of inquiry", "suara pertanyaan"],
    ["在", "zài", "in", "di"],
    ["风", "fēng", "wind", "angin"],
    ["中", "zhōng", "in", "dalam"],
    ["响起", "xiǎng qǐ", "sounded", "berbunyi"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第4段

    // ===== 第4段 =====
    ["“", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["在", "zài", "at", "di"],
    ["这儿", "zhè ér", "here", "di sini"],
    ["！", "", "", ""],
    ["”", "", "", ""],
    ["孩子", "hái zi", "children", "kanak-kanak"],
    ["们", "men", "", ""],
    ["的", "de", "", ""],
    ["回答声", "huí dá shēng", "voice of reply", "suara jawapan"],
    ["从", "cóng", "from", "dari"],
    ["四面八方", "sì miàn bā fāng", "all directions", "segenap arah"],
    ["传来", "chuán lái", "came", "datang"],
    ["。", "", "", ""],
    ["谁", "shuí", "who", "siapa"],
    ["和", "hé", "and", "dan"],
    ["谁", "shuí", "who", "siapa"],
    ["才", "cái", "only then", "barulah"],
    ["是", "shì", "is", "ialah"],
    ["一对", "yī duì", "a pair", "sepasang"],
    ["？", "", "", ""],
    ["哥哥", "gē ge", "older brother", "abang"],
    ["找到", "zhǎo dào", "found", "menemui"],
    ["妹妹", "mèi mei", "younger sister", "adik perempuan"],
    ["后", "hòu", "after", "selepas"],
    ["站", "zhàn", "stand", "berdiri"],
    ["在", "zài", "at", "di"],
    ["一起", "yī qǐ", "together", "bersama"],
    ["，", "", "", ""],
    ["有的", "yǒu de", "some", "sesetengah"],
    ["还", "hái", "still", "masih"],
    ["用", "yòng", "use", "menggunakan"],
    ["手", "shǒu", "hand", "tangan"],
    ["拉", "lā", "pull", "tarik"],
    ["着", "zhe", "", ""],
    ["手", "shǒu", "hand", "tangan"],
    ["，", "", "", ""],
    ["一起", "yī qǐ", "together", "bersama"],
    ["挽起", "wǎn qǐ", "roll up", "menggulung"],
    ["袖子", "xiù zi", "sleeves", "lengan baju"],
    ["，", "", "", ""],
    ["菜园", "cài yuán", "vegetable garden", "kebun sayur"],
    ["里", "lǐ", "in", "di"],
    ["闹哄哄", "nào hōng hōng", "noisy", "hingar bingar"],
    ["的", "de", "", ""],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第5段

    // ===== 第5段 =====
    ["“", "", "", ""],
    ["别", "bié", "don't", "jangan"],
    ["找", "zhǎo", "look for", "cari"],
    ["了", "le", "", ""],
    ["！", "", "", ""],
    ["”", "", "", ""],
    ["阿婆", "ā pó", "grandmother", "nenek"],
    ["笑着", "xiào zhe", "laughing", "sambil ketawa"],
    ["说", "shuō", "said", "berkata"],
    ["，", "", "", ""],
    ["“", "", "", ""],
    ["从", "cóng", "from", "dari"],
    ["现在", "xiàn zài", "now", "sekarang"],
    ["开始", "kāi shǐ", "start", "mula"],
    ["，", "", "", ""],
    ["我们", "wǒ men", "we", "kita"],
    ["用不着", "yòng bù zháo", "no need", "tidak perlu"],
    ["分队", "fēn duì", "split into teams", "berpecah kumpulan"],
    ["了", "le", "", ""],
    ["，", "", "", ""],
    ["每个人", "měi gè rén", "everyone", "setiap orang"],
    ["各自", "gè zì", "individually", "masing-masing"],
    ["找", "zhǎo", "find", "cari"],
    ["一样", "yī yàng", "one", "satu"],
    ["活儿", "huó ér", "work", "kerja"],
    ["干", "gàn", "do", "buat"],
    ["。", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第6段

    // ===== 第6段 =====
    ["孩子", "hái zi", "children", "kanak-kanak"],
    ["们", "men", "", ""],
    ["撒开腿", "sā kāi tuǐ", "ran freely", "berlari bebas"],
    ["，", "", "", ""],
    ["欢快", "huān kuài", "joyfully", "dengan gembira"],
    ["地", "de", "", ""],
    ["跑进", "pǎo jìn", "ran into", "berlari masuk"],
    ["了", "le", "", ""],
    ["菜园", "cài yuán", "vegetable garden", "kebun sayur"],
    ["。", "", "", ""],
    ["胆子大", "dǎn zi dà", "bold", "berani"],
    ["的", "de", "", ""],
    ["孩子", "hái zi", "children", "kanak-kanak"],
    ["争先恐后", "zhēng xiān kǒng hòu", "vying with each other", "berlumba-lumba"],
    ["地", "de", "", ""],
    ["踏过", "tà guò", "stepped over", "memijak"],
    ["水坑", "shuǐ kēng", "puddle", "lopak air"],
    ["，", "", "", ""],
    ["一脚", "yī jiǎo", "one foot", "satu kaki"],
    ["踩进", "cǎi jìn", "stepped into", "memijak masuk"],
    ["泥地", "ní dì", "muddy ground", "tanah berlumpur"],
    ["；", "", "", ""],
    ["那些", "nà xiē", "those", "itu"],
    ["胆子小", "dǎn zi xiǎo", "timid", "penakut"],
    ["的", "de", "", ""],
    ["孩子", "hái zi", "children", "kanak-kanak"],
    ["则", "zé", "then", "manakala"],
    ["踮着", "diǎn zhe", "tip-toe", "menjengket"],
    ["脚尖儿", "jiǎo jiān ér", "tiptoe", "hujung kaki"],
    ["，", "", "", ""],
    ["小心翼翼", "xiǎo xīn yì yì", "carefully", "berhati-hati"],
    ["地", "de", "", ""],
    ["绕过", "rào guò", "go around", "memintas"],
    ["泥地", "ní dì", "muddy ground", "tanah berlumpur"],
    ["。", "", "", ""],
    ["阿婆", "ā pó", "grandmother", "nenek"],
    ["的", "de", "", ""],
    ["脚步", "jiǎo bù", "footsteps", "langkah"],
    ["又轻又快", "yòu qīng yòu kuài", "light and fast", "ringan dan cepat"],
    ["，", "", "", ""],
    ["孩子", "hái zi", "children's", "kanak-kanak"],
    ["的", "de", "", ""],
    ["脚步", "jiǎo bù", "footsteps", "langkah"],
    ["却", "què", "but", "tetapi"],
    ["迈着", "mài zhe", "stepping", "melangkah"],
    ["迟缓", "chí huǎn", "slow", "perlahan"],
    ["而", "ér", "and", "dan"],
    ["稳重", "wěn zhòng", "steady", "stabil"],
    ["的", "de", "", ""],
    ["步子", "bù zi", "steps", "langkah"],
    ["。", "", "", ""],
    ["孩子", "hái zi", "children", "kanak-kanak"],
    ["们", "men", "", ""],
    ["终于", "zhōng yú", "finally", "akhirnya"],
    ["成为", "chéng wéi", "become", "menjadi"],
    ["自己", "zì jǐ", "own", "sendiri"],
    ["的", "de", "", ""],
    ["主人", "zhǔ rén", "master", "tuan"],
    ["，", "", "", ""],
    ["不再", "bù zài", "no longer", "tidak lagi"],
    ["受", "shòu", "receive", "menerima"],
    ["束缚", "shù fù", "restraint", "kekangan"],
    ["，", "", "", ""],
    ["纵情", "zòng qíng", "to one's heart's content", "sepuas hati"],
    ["地", "de", "", ""],
    ["挖土", "wā tǔ", "dig soil", "menggali tanah"],
    ["、", "", "", ""],
    ["浇水", "jiāo shuǐ", "water", "menyiram"],
    ["、", "", "", ""],
    ["捉虫", "zhuō chóng", "catch insects", "menangkap serangga"],
    ["，", "", "", ""],
    ["欢闹", "huān nào", "frolic", "berseronok"],
    ["了", "le", "", ""],
    ["一整个下午", "yī zhěng gè xià wǔ", "the whole afternoon", "sepanjang petang"],
    ["。", "", "", ""],
    ["瞬间", "shùn jiān", "instantly", "sekelip mata"],
    ["，", "", "", ""],
    ["夕阳", "xī yáng", "sunset", "matahari terbenam"],
    ["露出", "lù chū", "revealed", "menampakkan"],
    ["脸", "liǎn", "face", "muka"],
    ["来", "lái", "come", "datang"],
    ["，", "", "", ""],
    ["金色", "jīn sè", "golden", "keemasan"],
    ["的", "de", "", ""],
    ["光线", "guāng xiàn", "light", "cahaya"],
    ["驱走", "qū zǒu", "drove away", "menghalau"],
    ["了", "le", "", ""],
    ["炽热", "chì rè", "heat", "kepanasan"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第7段

    // ===== 第7段 =====
    ["“", "", "", ""],
    ["我们", "wǒ men", "we", "kita"],
    ["得", "děi", "must", "perlu"],
    ["在", "zài", "before", "sebelum"],
    ["晚饭", "wǎn fàn", "dinner", "makan malam"],
    ["之前", "zhī qián", "before", "sebelum"],
    ["回家", "huí jiā", "return home", "pulang ke rumah"],
    ["啊", "a", "", ""],
    ["！", "", "", ""],
    ["”", "", "", ""],
    ["孩子", "hái zi", "children", "kanak-kanak"],
    ["们", "men", "", ""],
    ["吵嚷", "chǎo rǎng", "clamoured", "hingar bingar"],
    ["着", "zhe", "", ""],
    ["……", "", "", ""],
    ["快乐", "kuài lè", "happy", "gembira"],
    ["的", "de", "", ""],
    ["劳动", "láo dòng", "labour", "kerja"],
    ["变成", "biàn chéng", "became", "menjadi"],
    ["了", "le", "", ""],
    ["不舍", "bù shě", "reluctant", "tidak sanggup"],
    ["的", "de", "", ""],
    ["告别", "gào bié", "farewell", "perpisahan"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第8段

    // ===== 第8段 =====
    ["乱了方寸", "luàn le fāng cùn", "lost composure", "hilang pertimbangan"],
    ["的", "de", "", ""],
    ["孩子", "hái zi", "children", "kanak-kanak"],
    ["们", "men", "", ""],
    ["顿时", "dùn shí", "immediately", "segera"],
    ["都", "dōu", "all", "semua"],
    ["舍不得", "shě bù dé", "cannot bear to", "tidak sanggup"],
    ["走", "zǒu", "leave", "pergi"],
    ["。", "", "", ""],
    ["夕阳西下", "xī yáng xī xià", "sun sets in the west", "matahari terbenam"],
    ["时", "shí", "when", "apabila"],
    ["，", "", "", ""],
    ["他们", "tā men", "they", "mereka"],
    ["还", "hái", "still", "masih"],
    ["在", "zài", "in", "di"],
    ["菜园", "cài yuán", "vegetable garden", "kebun sayur"],
    ["里", "lǐ", "in", "dalam"],
    ["依依不舍", "yī yī bù shě", "reluctant to part", "berat hati"],
    ["地", "de", "", ""],
    ["走", "zǒu", "walk", "berjalan"],
    ["着", "zhe", "", ""],
    ["……", "", "", ""],
    ["有个", "yǒu gè", "there was a", "ada seorang"],
    ["孩子", "hái zi", "child", "kanak-kanak"],
    ["被", "bèi", "by", "oleh"],
    ["自己", "zì jǐ", "own", "sendiri"],
    ["的", "de", "", ""],
    ["锄头", "chú tou", "hoe", "cangkul"],
    ["绊倒", "bàn dǎo", "tripped", "tersandung"],
    ["了", "le", "", ""],
    ["，", "", "", ""],
    ["鞋跟儿", "xié gēn ér", "heel", "tumit kasut"],
    ["踏着", "tà zhe", "stepped on", "memijak"],
    ["了", "le", "", ""],
    ["鞋尖儿", "xié jiān ér", "toe", "hujung kasut"],
    ["，", "", "", ""],
    ["有些", "yǒu xiē", "some", "sesetengah"],
    ["菜苗", "cài miáo", "vegetable seedlings", "anak benih sayur"],
    ["还", "hái", "still", "masih"],
    ["纠缠", "jiū chán", "entangled", "terbelit"],
    ["在", "zài", "at", "di"],
    ["一起", "yī qǐ", "together", "bersama"],
    ["了", "le", "", ""],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第9段

    // ===== 第9段 =====
    ["夕阳", "xī yáng", "sunset", "matahari terbenam"],
    ["越来越低", "yuè lái yuè dī", "lower and lower", "semakin rendah"],
    ["，", "", "", ""],
    ["孩子", "hái zi", "children", "kanak-kanak"],
    ["们", "men", "", ""],
    ["仍", "réng", "still", "masih"],
    ["在", "zài", "in", "di"],
    ["菜园", "cài yuán", "vegetable garden", "kebun sayur"],
    ["里", "lǐ", "in", "dalam"],
    ["马不停蹄", "mǎ bù tíng tí", "non-stop", "tanpa henti"],
    ["地", "de", "", ""],
    ["干", "gàn", "work", "kerja"],
    ["着", "zhe", "", ""],
    ["活儿", "huó ér", "work", "kerja"],
    ["，", "", "", ""],
    ["同时", "tóng shí", "at the same time", "pada masa yang sama"],
    ["大呼小叫", "dà hū xiǎo jiào", "shouting", "menjerit-jerit"],
    ["。", "", "", ""],
    ["许多", "xǔ duō", "many", "banyak"],
    ["孩子", "hái zi", "children", "kanak-kanak"],
    ["抬头", "tái tóu", "look up", "mendongak"],
    ["望向", "wàng xiàng", "look towards", "memandang ke"],
    ["自己", "zì jǐ", "own", "sendiri"],
    ["所", "suǒ", "that", "yang"],
    ["能", "néng", "can", "boleh"],
    ["看到", "kàn dào", "see", "melihat"],
    ["的", "de", "", ""],
    ["第一颗", "dì yī kē", "first", "pertama"],
    ["星星", "xīng xing", "star", "bintang"],
    ["，", "", "", ""],
    ["把", "bǎ", "", ""],
    ["自己", "zì jǐ", "themselves", "diri sendiri"],
    ["安顿", "ān dùn", "settle", "menempatkan"],
    ["在", "zài", "at", "di"],
    ["所", "suǒ", "that", "yang"],
    ["能", "néng", "can", "boleh"],
    ["找到", "zhǎo dào", "find", "menemui"],
    ["的", "de", "", ""],
    ["第一片", "dì yī piàn", "first", "pertama"],
    ["草地", "cǎo dì", "grassland", "padang rumput"],
    ["上", "shàng", "on", "atas"],
    ["。", "", "", ""],
    ["阿婆", "ā pó", "grandmother", "nenek"],
    ["站起来", "zhàn qǐ lái", "stood up", "berdiri"],
    ["后", "hòu", "after", "selepas"],
    ["，", "", "", ""],
    ["在", "zài", "at", "di"],
    ["菜畦", "cài qí", "vegetable bed", "batas sayur"],
    ["边", "biān", "side", "tepi"],
    ["发现", "fā xiàn", "discovered", "menemui"],
    ["了", "le", "", ""],
    ["一只", "yī zhī", "a", "sebuah"],
    ["大婶", "dà shěn", "auntie's", "mak cik"],
    ["的", "de", "", ""],
    ["篮子", "lán zi", "basket", "bakul"],
    ["、", "", "", ""],
    ["一只", "yī zhī", "a", "sebuah"],
    ["蓝色", "lán sè", "blue", "biru"],
    ["的", "de", "", ""],
    ["水壶", "shuǐ hú", "kettle", "cerek air"],
    ["、", "", "", ""],
    ["一只", "yī zhī", "a", "sebuah"],
    ["左手", "zuǒ shǒu", "left hand", "tangan kiri"],
    ["的", "de", "", ""],
    ["手套", "shǒu tào", "glove", "sarung tangan"],
    ["，", "", "", ""],
    ["还有", "hái yǒu", "also have", "masih ada"],
    ["一只", "yī zhī", "a", "sebuah"],
    ["男孩儿", "nán hái ér", "boy's", "budak lelaki"],
    ["的", "de", "", ""],
    ["右手", "yòu shǒu", "right hand", "tangan kanan"],
    ["铲子", "chǎn zi", "shovel", "penyodok"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第10段

    // ===== 第10段 =====
    ["“", "", "", ""],
    ["这", "zhè", "this", "ini"],
    ["到底", "dào dǐ", "on earth", "sebenarnya"],
    ["……", "", "", ""],
    ["”", "", "", ""],
    ["阿婆", "ā pó", "grandmother", "nenek"],
    ["说", "shuō", "said", "berkata"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第11段

    // ===== 第11段 =====
    ["“", "", "", ""],
    ["这", "zhè", "this", "ini"],
    ["到底", "dào dǐ", "on earth", "sebenarnya"],
    ["……", "", "", ""],
    ["”", "", "", ""],
    ["全村", "quán cūn", "whole village", "seluruh kampung"],
    ["的", "de", "", ""],
    ["人", "rén", "people", "orang"],
    ["看到", "kàn dào", "saw", "melihat"],
    ["菜园", "cài yuán", "vegetable garden", "kebun sayur"],
    ["变得", "biàn de", "became", "menjadi"],
    ["整整齐齐", "zhěng zhěng qí qí", "neat and tidy", "tersusun rapi"],
    ["时", "shí", "when", "apabila"],
    ["都", "dōu", "all", "semua"],
    ["这么", "zhè me", "so", "begitu"],
    ["说", "shuō", "said", "berkata"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第12段

    // ===== 第12段 =====
    ["那天", "nà tiān", "that day", "hari itu"],
    ["傍晚", "bàng wǎn", "evening", "waktu senja"],
    ["，", "", "", ""],
    ["人们", "rén men", "people", "orang ramai"],
    ["只好", "zhǐ hǎo", "had no choice but", "terpaksa"],
    ["一拐一拐", "yī guǎi yī guǎi", "limping", "terhinggut-hinggut"],
    ["地", "de", "", ""],
    ["走回家", "zǒu huí jiā", "walk home", "berjalan pulang"],
    ["、", "", "", ""],
    ["去吃饭", "qù chī fàn", "go eat", "pergi makan"],
    ["，", "", "", ""],
    ["因", "yīn", "because", "kerana"],
    ["他们", "tā men", "their", "mereka"],
    ["的", "de", "", ""],
    ["手", "shǒu", "hands", "tangan"],
    ["都", "dōu", "all", "semua"],
    ["沾满", "zhān mǎn", "covered with", "penuh dengan"],
    ["了", "le", "", ""],
    ["泥巴", "ní bā", "mud", "lumpur"],
    ["，", "", "", ""],
    ["不是", "bù shì", "either", "sama ada"],
    ["太脏", "tài zāng", "too dirty", "terlalu kotor"],
    ["就是", "jiù shì", "or", "atau"],
    ["太湿", "tài shī", "too wet", "terlalu basah"],
    ["，", "", "", ""],
    ["要不", "yào bù", "otherwise", "kalau tidak"],
    ["就", "jiù", "then", "lalu"],
    ["都是", "dōu shì", "all are", "semuanya"],
    ["黑泥巴", "hēi ní bā", "black mud", "lumpur hitam"],
    ["，", "", "", ""],
    ["或", "huò", "or", "atau"],
    ["全都", "quán dōu", "all", "semua"],
    ["是", "shì", "are", "ialah"],
    ["湿泥巴", "shī ní bā", "wet mud", "lumpur basah"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第13段

    // ===== 第13段 =====
    ["人们", "rén men", "People", "Orang ramai"],
    ["挠着", "náo zhe", "scratching", "menggaru"],
    ["头", "tóu", "head", "kepala"],
    ["相互", "xiāng hù", "each other", "saling"],
    ["问", "wèn", "asked", "bertanya"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["我", "wǒ", "my", "saya"],
    ["的", "de", "", ""],
    ["手套", "shǒu tào", "glove", "sarung tangan"],
    ["在", "zài", "at", "di"],
    ["哪儿", "nǎ ér", "where", "di mana"],
    ["啊", "a", "", ""],
    ["？", "", "", ""],
    ["谁", "shuí", "who", "siapa"],
    ["拿", "ná", "took", "mengambil"],
    ["了", "le", "", ""],
    ["我", "wǒ", "my", "saya"],
    ["的", "de", "", ""],
    ["铲子", "chǎn zi", "shovel", "penyodok"],
    ["啊", "a", "", ""],
    ["？", "", "", ""],
    ["”", "", "", ""],
    ["大家", "dà jiā", "everyone", "semua orang"],
    ["相互", "xiāng hù", "each other", "saling"],
    ["查看", "chá kàn", "checked", "memeriksa"],
    ["对方", "duì fāng", "the other party", "pihak lain"],
    ["的", "de", "", ""],
    ["手", "shǒu", "hands", "tangan"],
    ["，", "", "", ""],
    ["不时", "bù shí", "from time to time", "kadang-kadang"],
    ["听到", "tīng dào", "heard", "mendengar"],
    ["有人", "yǒu rén", "someone", "seseorang"],
    ["喊", "hǎn", "shout", "jerit"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["啊", "a", "ah", "ah"],
    ["，", "", "", ""],
    ["我", "wǒ", "my", "saya"],
    ["的", "de", "", ""],
    ["棕色", "zōng sè", "brown", "coklat"],
    ["手套", "shǒu tào", "glove", "sarung tangan"],
    ["在", "zài", "at", "di"],
    ["那儿", "nà ér", "there", "sana"],
    ["！", "", "", ""],
    ["”", "", "", ""],
    ["或者", "huò zhě", "or", "atau"],
    ["，", "", "", ""],
    ["“", "", "", ""],
    ["你", "nǐ", "you", "awak"],
    ["拿", "ná", "took", "mengambil"],
    ["的", "de", "", ""],
    ["是", "shì", "is", "ialah"],
    ["我", "wǒ", "my", "saya"],
    ["的", "de", "", ""],
    ["桃红色", "táo hóng sè", "pink", "merah jambu"],
    ["水壶", "shuǐ hú", "kettle", "cerek air"],
    ["……", "", "", ""],
    ["”", "", "", ""],
    ["过了", "guò le", "after", "selepas"],
    ["好一阵子", "hǎo yī zhèn zi", "quite a while", "agak lama"],
    ["，", "", "", ""],
    ["人们", "rén men", "people", "orang ramai"],
    ["都", "dōu", "all", "semua"],
    ["找回", "zhǎo huí", "found back", "menemui semula"],
    ["了", "le", "", ""],
    ["自己", "zì jǐ", "own", "sendiri"],
    ["的", "de", "", ""],
    ["工具", "gōng jù", "tools", "alat"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第14段

    // ===== 第14段 =====
    ["只有", "zhǐ yǒu", "only", "hanya"],
    ["阿婆", "ā pó", "grandmother", "nenek"],
    ["的", "de", "", ""],
    ["工夫", "gōng fu", "effort", "usaha"],
    ["长", "cháng", "long", "panjang"],
    ["一些", "yī xiē", "some", "sedikit"],
    ["，", "", "", ""],
    ["因为", "yīn wèi", "because", "kerana"],
    ["她", "tā", "her", "dia"],
    ["那棵", "nà kē", "that", "itu"],
    ["淘气", "táo qì", "naughty", "nakal"],
    ["的", "de", "", ""],
    ["菜苗", "cài miáo", "vegetable seedling", "anak benih sayur"],
    ["被", "bèi", "by", "oleh"],
    ["遗忘", "yí wàng", "forgotten", "dilupakan"],
    ["在", "zài", "at", "di"],
    ["菜园", "cài yuán", "vegetable garden", "kebun sayur"],
    ["的", "de", "", ""],
    ["角落", "jiǎo luò", "corner", "penjuru"],
    ["，", "", "", ""],
    ["三天", "sān tiān", "three days", "tiga hari"],
    ["以后", "yǐ hòu", "later", "kemudian"],
    ["才", "cái", "only then", "barulah"],
    ["被", "bèi", "by", "oleh"],
    ["雨水", "yǔ shuǐ", "rainwater", "air hujan"],
    ["浇出", "jiāo chū", "watered out", "disiram keluar"],
    ["了", "le", "", ""],
    ["嫩芽", "nèn yá", "tender shoots", "pucuk muda"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第15段

    // ===== 第15段 =====
    ["阿婆", "ā pó", "grandmother", "nenek"],
    ["把", "bǎ", "", ""],
    ["那棵", "nà kē", "that", "itu"],
    ["菜苗", "cài miáo", "vegetable seedling", "anak benih sayur"],
    ["小心", "xiǎo xīn", "carefully", "berhati-hati"],
    ["地", "de", "", ""],
    ["移到", "yí dào", "moved to", "dipindahkan ke"],
    ["菜畦", "cài qí", "vegetable bed", "batas sayur"],
    ["中央", "zhōng yāng", "centre", "tengah"],
    ["，", "", "", ""],
    ["轻轻", "qīng qīng", "gently", "perlahan"],
    ["地", "de", "", ""],
    ["浇上", "jiāo shàng", "watered", "menyiram"],
    ["水", "shuǐ", "water", "air"],
    ["。", "", "", ""],
    ["她", "tā", "she", "dia"],
    ["对", "duì", "to", "kepada"],
    ["小孙女", "xiǎo sūn nǚ", "little granddaughter", "cucu perempuan kecil"],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["你", "nǐ", "you", "awak"],
    ["看", "kàn", "look", "lihat"],
    ["，", "", "", ""],
    ["一粒", "yī lì", "one grain", "satu biji"],
    ["小小", "xiǎo xiǎo", "small", "kecil"],
    ["的", "de", "", ""],
    ["种子", "zhǒng zi", "seed", "benih"],
    ["，", "", "", ""],
    ["埋在", "mái zài", "buried in", "tertanam di"],
    ["土里", "tǔ lǐ", "in the soil", "dalam tanah"],
    ["，", "", "", ""],
    ["看不见", "kàn bù jiàn", "cannot see", "tidak nampak"],
    ["光", "guāng", "light", "cahaya"],
    ["，", "", "", ""],
    ["也", "yě", "also", "juga"],
    ["看不见", "kàn bù jiàn", "cannot see", "tidak nampak"],
    ["天", "tiān", "sky", "langit"],
    ["。", "", "", ""],
    ["可是", "kě shì", "but", "tetapi"],
    ["它", "tā", "it", "ia"],
    ["从没", "cóng méi", "never", "tidak pernah"],
    ["放弃", "fàng qì", "give up", "berputus asa"],
    ["，", "", "", ""],
    ["一天", "yī tiān", "day by day", "hari demi hari"],
    ["一天", "yī tiān", "day by day", "hari demi hari"],
    ["地", "de", "", ""],
    ["长", "zhǎng", "grow", "tumbuh"],
    ["，", "", "", ""],
    ["最后", "zuì hòu", "finally", "akhirnya"],
    ["就", "jiù", "then", "lalu"],
    ["变成", "biàn chéng", "become", "menjadi"],
    ["了", "le", "", ""],
    ["我们", "wǒ men", "our", "kita"],
    ["餐桌", "cān zhuō", "dining table", "meja makan"],
    ["上", "shàng", "on", "atas"],
    ["的", "de", "", ""],
    ["菜", "cài", "dish", "hidangan"],
    ["。", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第16段

    // ===== 第16段 =====
    ["小孙女", "xiǎo sūn nǚ", "little granddaughter", "cucu perempuan kecil"],
    ["歪着", "wāi zhe", "tilting", "miringkan"],
    ["头", "tóu", "head", "kepala"],
    ["问", "wèn", "asked", "bertanya"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["那", "nà", "then", "jadi"],
    ["它", "tā", "it", "ia"],
    ["不", "bù", "not", "tidak"],
    ["觉得", "jué de", "feel", "rasa"],
    ["累", "lèi", "tired", "letih"],
    ["吗", "ma", "", ""],
    ["？", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第17段

    // ===== 第17段 =====
    ["阿婆", "ā pó", "grandmother", "nenek"],
    ["笑了", "xiào le", "laughed", "ketawa"],
    ["，", "", "", ""],
    ["摸了摸", "mō le mō", "stroked", "mengusap"],
    ["她", "tā", "her", "dia"],
    ["的", "de", "", ""],
    ["头", "tóu", "head", "kepala"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["它", "tā", "it", "ia"],
    ["累", "lèi", "tired", "letih"],
    ["，", "", "", ""],
    ["可是", "kě shì", "but", "tetapi"],
    ["它", "tā", "it", "ia"],
    ["知道", "zhī dào", "knows", "tahu"],
    ["，", "", "", ""],
    ["它", "tā", "its", "ia"],
    ["的", "de", "", ""],
    ["努力", "nǔ lì", "effort", "usaha"],
    ["，", "", "", ""],
    ["会", "huì", "will", "akan"],
    ["让", "ràng", "let", "membuat"],
    ["别人", "bié rén", "others", "orang lain"],
    ["吃饱", "chī bǎo", "eat full", "makan kenyang"],
    ["，", "", "", ""],
    ["会", "huì", "will", "akan"],
    ["让", "ràng", "let", "membuat"],
    ["别人", "bié rén", "others", "orang lain"],
    ["开心", "kāi xīn", "happy", "gembira"],
    ["。", "", "", ""],
    ["这", "zhè", "this", "ini"],
    ["就是", "jiù shì", "is", "adalah"],
    ["它", "tā", "it", "ia"],
    ["活着", "huó zhe", "living", "hidup"],
    ["的", "de", "", ""],
    ["意义", "yì yì", "meaning", "makna"],
    ["。", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第18段

    // ===== 第18段 =====
    ["小孙女", "xiǎo sūn nǚ", "little granddaughter", "cucu perempuan kecil"],
    ["似懂非懂", "sì dǒng fēi dǒng", "half-understanding", "separuh faham"],
    ["地", "de", "", ""],
    ["点", "diǎn", "nodded", "mengangguk"],
    ["了", "le", "", ""],
    ["点头", "diǎn tóu", "nod", "mengangguk"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第19段

    // ===== 第19段 =====
    ["从", "cóng", "from", "dari"],
    ["那天", "nà tiān", "that day", "hari itu"],
    ["起", "qǐ", "onwards", "semenjak"],
    ["，", "", "", ""],
    ["她", "tā", "she", "dia"],
    ["每天", "měi tiān", "every day", "setiap hari"],
    ["放学", "fàng xué", "school ends", "tamat sekolah"],
    ["后", "hòu", "after", "selepas"],
    ["都", "dōu", "all", "semua"],
    ["跑", "pǎo", "run", "berlari"],
    ["来", "lái", "come", "datang"],
    ["看", "kàn", "see", "melihat"],
    ["那棵", "nà kē", "that", "itu"],
    ["菜苗", "cài miáo", "vegetable seedling", "anak benih sayur"],
    ["，", "", "", ""],
    ["给", "gěi", "for", "untuk"],
    ["它", "tā", "it", "ia"],
    ["浇水", "jiāo shuǐ", "water", "menyiram"],
    ["、", "", "", ""],
    ["拔草", "bá cǎo", "pull weeds", "merumput"],
    ["、", "", "", ""],
    ["捉虫", "zhuō chóng", "catch insects", "menangkap serangga"],
    ["。", "", "", ""],
    ["日子", "rì zi", "days", "hari-hari"],
    ["一天天", "yī tiān tiān", "day by day", "hari demi hari"],
    ["过去", "guò qù", "passed", "berlalu"],
    ["，", "", "", ""],
    ["菜苗", "cài miáo", "vegetable seedling", "anak benih sayur"],
    ["一天天", "yī tiān tiān", "day by day", "hari demi hari"],
    ["长高", "zhǎng gāo", "grew taller", "tumbuh tinggi"],
    ["，", "", "", ""],
    ["最后", "zuì hòu", "finally", "akhirnya"],
    ["真的", "zhēn de", "really", "benar-benar"],
    ["变成", "biàn chéng", "became", "menjadi"],
    ["了", "le", "", ""],
    ["餐桌", "cān zhuō", "dining table", "meja makan"],
    ["上", "shàng", "on", "atas"],
    ["一道", "yī dào", "a", "satu"],
    ["热腾腾", "rè téng téng", "steaming hot", "panas menggelegak"],
    ["的", "de", "", ""],
    ["菜", "cài", "dish", "hidangan"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第20段

    // ===== 第20段 =====
    ["那天", "nà tiān", "that day", "hari itu"],
    ["晚上", "wǎn shàng", "evening", "malam"],
    ["，", "", "", ""],
    ["全家人", "quán jiā rén", "whole family", "sekeluarga"],
    ["围坐", "wéi zuò", "sit around", "duduk mengelilingi"],
    ["在", "zài", "at", "di"],
    ["一起", "yī qǐ", "together", "bersama"],
    ["吃饭", "chī fàn", "eat", "makan"],
    ["。", "", "", ""],
    ["小孙女", "xiǎo sūn nǚ", "little granddaughter", "cucu perempuan kecil"],
    ["忽然", "hū rán", "suddenly", "tiba-tiba"],
    ["抬起头", "tái qǐ tóu", "looked up", "mendongak"],
    ["，", "", "", ""],
    ["对", "duì", "to", "kepada"],
    ["阿婆", "ā pó", "grandmother", "nenek"],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["阿婆", "ā pó", "grandmother", "nenek"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["以后", "yǐ hòu", "in future", "masa depan"],
    ["也", "yě", "also", "juga"],
    ["要", "yào", "want", "mahu"],
    ["像", "xiàng", "like", "seperti"],
    ["那棵", "nà kē", "that", "itu"],
    ["菜", "cài", "vegetable", "sayur"],
    ["一样", "yī yàng", "same", "sama"],
    ["，", "", "", ""],
    ["好好", "hǎo hǎo", "well", "dengan baik"],
    ["长大", "zhǎng dà", "grow up", "membesar"],
    ["，", "", "", ""],
    ["让", "ràng", "let", "membuat"],
    ["大家", "dà jiā", "everyone", "semua orang"],
    ["都", "dōu", "all", "semua"],
    ["开心", "kāi xīn", "happy", "gembira"],
    ["。", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第21段

    // ===== 第21段 =====
    ["阿婆", "ā pó", "grandmother's", "nenek"],
    ["的", "de", "", ""],
    ["眼睛", "yǎn jīng", "eyes", "mata"],
    ["湿润", "shī rùn", "moist", "lembap"],
    ["了", "le", "", ""],
    ["，", "", "", ""],
    ["她", "tā", "she", "dia"],
    ["夹了", "jiā le", "picked up", "mengambil"],
    ["一筷子", "yī kuài zi", "a chopstick-ful", "sepenyepit"],
    ["菜", "cài", "vegetable", "sayur"],
    ["放进", "fàng jìn", "put into", "memasukkan"],
    ["小孙女", "xiǎo sūn nǚ", "little granddaughter's", "cucu perempuan kecil"],
    ["的", "de", "", ""],
    ["碗里", "wǎn lǐ", "bowl", "dalam mangkuk"],
    ["，", "", "", ""],
    ["轻声", "qīng shēng", "softly", "perlahan"],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["好", "hǎo", "good", "baik"],
    ["，", "", "", ""],
    ["阿婆", "ā pó", "grandmother", "nenek"],
    ["等着", "děng zhe", "waiting", "menunggu"],
    ["。", "", "", ""],
    ["”", "", "", ""],
];

// 如果使用模块导出，取消下一行注释；若通过 script 标签引入，则全局可用
// export { lessonTitle, lessonData };
